### PR TITLE
📦 Add linkcheck action

### PR DESCRIPTION
**Pull request by TechWiz-3**
First of all, thank you for your work on this project 👍 

In this PR, I have added a workflow which checks links and fails if any of them are broken. The workflow runs everyday and on pushes.

Disclaimer: this action is my own action, the repo is [here](https://github.com/TechWiz-3/linksafe)

You can view the logs of the workflow on my fork [here](https://github.com/TechWiz-3/awesome-asyncio/runs/8127175456?check_suite_focus=true). 1 link was found to be broken.

Let me know if you'd like me to change anything, any feedback is appreciated either way :)

### CODE REVIEW

**Comment by timofurrer** [comment]
@TechWiz-3 Thanks for the contribution! 

I'm wondering, what is the advantage your action has vs. a more widely used one like https://github.com/gaurav-nelson/github-action-markdown-link-check ?

**Comment by TechWiz-3** [comment]
Not much really, other more popular versions are more developed so you can use stuff like config files, except status codes as well as certain links etc. Currently I'm working on these features but it'll be some time.

If you are looking for a really powerful, high performance link checker I'd recommend [lychee](https://github.com/lycheeverse/lychee-action), lychee is like a farrari. On the other hand if you'd like to support a local Toyota Camry manufacturer that one day could make farraris, I'd recommend using `linksafe`

**Comment by timofurrer** [comment]
We have the [`awesome-bot`](https://github.com/timofurrer/awesome-asyncio/blob/main/.github/workflows/awesomebot.yml) in place now. I'm going to close here.

Thanks for the suggestion 🤝

**Comment by TechWiz-3** [comment]
🤝

**Pull request closed without merging**
