### PR TITLE
Add loafer

### PR DESCRIPTION
**Pull request by daneoshiga**
# What is this project?

It abstracts the consumption of SQS messages using asyncio

http://loafer.readthedocs.io/en/latest/

Features:
- Encourages decoupling from message providers and consumers
- Easy to extend and customize
- Easy error handling, including integration with sentry
- Easy to create one or multiple services
- Generic Handlers
- Amazon SQS integration

# Why is it awesome?

When using it, you don't need to worry about asyncio and the event-loop, it's all abstracted away, you can even write sync code that it will deal with it just fine.

### CODE REVIEW

**Comment by timofurrer** [comment]
Looks good to me. Anyone else what to comment on that?

**Comment by timofurrer** [comment]
Please resolve the conflicts 🎉

**Comment by timofurrer** [comment]
`loafer` doesn't really seem to be maintained. @daneoshiga do you still think this should be included in the list?

**Comment by daneoshiga** [comment]
@timofurrer no, I think it's OK to not add it any more.

**Pull request closed without merging**
