### PR TITLE
add autobahn and crossbar

### PR DESCRIPTION
**Pull request by oberstet**

### CODE REVIEW

**Comment by timofurrer** [comment]
Thanks for the contribution. :beers: However, `crossbar.io` does not seem like a resource which belongs here. 

It would be nice if you could also reason about why those projects are awesome!

**Comment by oberstet** [comment]
@timofurrer Sure! I've kindly asked Roger to comment .. please see [here](https://groups.google.com/forum/#!topic/crossbario/91SDS27NWs8).

**Comment by timofurrer** [comment]
Great! Thanks for avoiding self-promotion :+1:

**Comment by oddjobz** [comment]
If it's of any help, as a long-term user;
> A complete set of libraries and tools for writing high performance, low latency, websockets based applications, ideal for both IoT solutions, websites, and modern Single Page Applications. As a true polyglot framework, it's the most advanced and complete approach I've come across for the implementation of true micro-service based solutions.

**Comment by timofurrer** [comment]
That definitely helps - Thanks! However, I'm curious about Roger's feedback :)

**Comment by oberstet** [comment]
@timofurrer Sure. But to be honest, this seems to be the first case where you require feedback from multiple users - or any feedback at all. This is the first PR, so how did you check the projects already in the list?

**Comment by timofurrer** [comment]
... my own humble opinion ;) Point Taken.

I'm going to merge it - I'm still curious and that's why I leave this PR open for some time.

**Comment by oddjobz** [comment]
Well if you're worried about me / my comments being 'real', my main live project is https://i.needacandidate.today, which is 100% crossbar + autobahn, no nginx or apache (or anything else) in sight, and you can whois me on "linux.co.uk" or "linux.uk". I've no commercial relationship with Tavendo whatsoever, my only connection is that I reviewed the available options a few years back and Crossbar won hands-down. (I've not seen anything to touch it since then) My comments may not be terribly eloquent, but from a technical perspective I think they're accurate and relatively concise.

**Comment by oberstet** [comment]
Gareth, you've made my day=) I've invested countless hours contributing to this tech stack, and it's just good to read how it helped you building your app. NeedACandidate looks awesome. Nice, nice!

**Comment by oddjobz** [comment]
I've developed web apps using a variety of technologies, including PHP, Ajax, ExtJS/Direct etc etc .. the websocket/RPC/PUB/SUB approach is SO different it's untrue. Without wanting to sound too much like a parrot, I think you under-hype the benefits to web / application designers, IoT is still pretty niche but there are a hell of a lot of people out there trying to write microservices based projects using Java who could get better results 10x quicker using Crossbar/Python.

**Comment by oberstet** [comment]
@oddjobz  A story I often hear from developers new to this tech stack is: "First, I didn't get it (so much stuff, async is hard, your docs suck, etc). Once I got it, understood the WAMP ecosystem and how things fit together, it does indeed make sense and I don't want to go back!"

WAMP in general (and Crossbar.io + Python in particular of course;) makes it easy to create general microservice based apps and modern Web real-time interactive user experiences. Yes, we "under-hype" that use case, and our "marketing message" is skewed towards IoT. This is a deliberate decision we (Tavendo) took after much discussions. Reasons include:

* "modern Web framework" is a crowded place
* crisper marketing message
* IoT will be huge
* business strategy

But that doesn't mean we don't wanna help poor sad Java enterprise developers see the light;)

@timofurrer Sorry for hijacking / OTing this thread;) Hope you don't mind. FWIW, we do advocate for the new Python 3.5 async/await style - eg we've recently rewrote all Autobahn examples to that style, eg [here](https://github.com/crossbario/autobahn-python/tree/master/examples/asyncio/wamp/overview).

**Comment by oddjobz** [comment]
And your story is the raison d'etre for iFlex Studio .. :) , i.e. you can create a complete working SSL based website with a couple of client certificate authenticating Microservices and oAuth user authentication deployed in a container, in around 60 seconds ... watch this space .. :) .. Incidentally, the reason I initially chose Crossbar was that I was working on an IoT type system (distributed door entry) and wanted a single solution for devices, AND for the central control panel .. (!)

**Comment by timofurrer** [comment]
> Well if you're worried about me / my comments being 'real', my main live project is 

I wasn't, no worries :)

Thanks for your statements. I'll merge it now ... @Roger, if you are here one day: I'm still curious :stuck_out_tongue:

**Pull request merged**
