### PR TITLE
two additional orms

### PR DESCRIPTION
**Pull request by kszucs**
# What is this project?

- asyncorm
- aiopeewee

Please add a link in this pull request.

# Why is it awesome?

- asyncio native
- wrappers for two popular orms

### CODE REVIEW

**Comment by timofurrer** [comment]
**ayncorm**: this project seems to be in beta state and wip. Thus, I think it's best to wait until it's in a more stable phase of development - how do I know if it's still *awesome* it the end?

**aiopeewee**: could you elaborate why it's better than the already added: [peewee-async](https://github.com/05bit/peewee-async)

**Comment by kszucs** [comment]
Every one of them are in kind of `beta` state. We could maybe split to an orm section. Asyncio doesn't really have a mature orm BTW. 

Aiopeewee's syntax is closer what a developer would expect from an asyncio orm.

**Comment by timofurrer** [comment]
please resolve the conflicts 🌮

**Comment by timofurrer** [comment]
Please adhere to the [Contribution Guidelines](https://github.com/timofurrer/awesome-asyncio/blob/master/CONTRIBUTING.md)

**Comment by kszucs** [comment]
Sorry, I forget about this PR.

**Pull request closed without merging**
