### PR TITLE
Add Starlette.

### PR DESCRIPTION
**Pull request by olivertso**
Starlette is a lightweight ASGI framework/toolkit for building high performance services. You can use any of its components independently.

Some of its features:
- WebSocket support.
- GraphQL support.
- In-process background tasks.
- 100% type annotated codebase.
- Zero hard dependencies.

This one does not count as a feature, but still worth mentioning: it's made by the same author of Django REST framework.

The only drawback is that it's still a relatively young project.

### CODE REVIEW

**Comment by timofurrer** [comment]
It really looks like a promising framework. Let's leave this PR open and see what happens with the project for a little longer.

If there is a lot of request to include starlette here, I'll merge this PR though 🎉

**Comment by olivertso** [comment]
@timofurrer Great, thanks for the feedback!

**Comment by timofurrer** [comment]
Please resolve the conflicts.

**Comment by timofurrer** [comment]
Thanks 🎄 🎉

**Pull request merged**
