### PR TITLE
asynccli

### PR DESCRIPTION
**Pull request by ahopkins**
# What is this project?

A command line interface framework built off `acyncio` called [asynccli](https://github.com/ahopkins/asynccli).

# Why is it awesome?

- Most other CLI frameworks in Python do not have `asyncio` support out of the box. This is designed specifically around asynchronous CLI tool development
- It allows for real simple calls by a single function, or more extensive class based definitions that allow for nesting and arguments

### CODE REVIEW

**Comment by timofurrer** [comment]
With some more :tada: or :+1: I'll merge it.
For now it seems like not really widely used. And to be honest, I don't fully understand it's benefit - maybe you can elaborate on why it's awesome and why it's needed?

**Comment by ahopkins** [comment]
I began a project using the [Sanic framework](https://github.com/channelcat/sanic). The whole framework runs on an event loop.

I needed to integrate some CLI commands and to be able to execute some of the same functionality that was built into my API using `async` and `await`. However, the regular CLI tools were not sufficient because they did not out of the box support these operations.

**Comment by timofurrer** [comment]
Please resolve the conflicts 🎉

**Comment by timofurrer** [comment]
Since this PR still has conflicts and for `asynccli` haven't been any contributions in years I'm going to close this here.

**Pull request closed without merging**
