### PR TITLE
Add alphabetical order in the contents menu

### PR DESCRIPTION
**Pull request by Marcelo-Theodoro**
Change the contents menu to be in alphabetical order. It really makes easier to find something when the list grows.

What do you think guys and girls?

### CODE REVIEW

**Comment by timofurrer** [comment]
Thanks 🎉 

I like the alphabetical ordering, however I've also appreciated *Writings* and *Talks* at the bottom, since those are not directly Frameworks or Libraries. What do you think?

Maybe just order the others?

**Comment by Marcelo-Theodoro** [comment]
I think it really makes sense.
So we just add the Writing and Talks at the bottom of the list? Or we need some kind of separator?

**Comment by timofurrer** [comment]
I think at the bottom of the list is fine :)

**Comment by timofurrer** [comment]
🎉

**Pull request merged**
