### PR TITLE
Twisted as asyncio alternative

### PR DESCRIPTION
**Pull request by rooterkyberian**
# What is this project?

Twisted is a mature Python2/3 async framework with bunch of network protocol implementations built-in.

**Note:** Please respect the [Contribution Guidelines](https://github.com/timofurrer/awesome-asyncio/blob/master/CONTRIBUTING.md)!

# Why is it awesome?

Twisted AFAIK at some point was THE solution for async in Python, and because of that even if it lags behind right now it is biggest competitor for `asyncio`.
Batteries included (implements number of different protocols).

I have added a link which explains how it can be used on top of asyncio loop. I have not linked to the official documentation (instead opting to link official bug tracker) as the auto-generated documentation isn't too helpful as it contains only one-line description.

### CODE REVIEW

**Comment by timofurrer** [comment]
Please adhere to the [Contribution Guidelines](https://github.com/timofurrer/awesome-asyncio/blob/master/CONTRIBUTING.md)

**Comment by rooterkyberian** [comment]
> Add one link per Pull Request.

while PR had two links, both refered to the same project - one was for the main website and other to explaination (which is otherwise hard to find) that refers to asyncio integration.

> Don't mention asyncio in the description as it's implied.

with Twisted it is not, since it has been out there long before `asyncio` module

**Comment by timofurrer** [comment]
I see your points.

How popular is it to use this asyncio-based reactor with twisted?

**Comment by rooterkyberian** [comment]
Not much ( https://github.com/search?l=Python&q=twisted+asyncioreactor&type=Code ).
Should I remove that link and resubmit Twisted alone?

**Comment by timofurrer** [comment]
I think it'd make more sense. And the link is not really intuitive, too.

**Pull request closed without merging**
